name: "Send Email after workflow completion"

on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          # No need to install smtplib; it’s in Python standard library

      - name: Debug env vars
        run: |
          echo "SENDER_EMAIL=$SENDER_EMAIL"
          echo "RECEIVER_EMAIL=$RECEIVER_EMAIL"
          echo "SENDER_PASSWORD length: ${#SENDER_PASSWORD}"
          echo "WORKFLOW_NAME=$WORKFLOW_NAME"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
        env:
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          WORKFLOW_NAME: ${{ github.workflow }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}

      - name: "Send Email by executing Python script"
        run: python script.py
        env:
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          WORKFLOW_NAME: ${{ github.workflow }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
